// Generated by CoffeeScript 1.10.0
(function() {
  var ages, k, v;

  ages = {};

  ages["jim"] = 12;

  ages["john"] = 7;

  for (k in ages) {
    v = ages[k];
    console.log(k + " is " + v);
  }

}).call(this);
