// Generated by CoffeeScript 1.10.0
(function() {
  var c, f, fs, tabdown;

  tabdown = require('tabdown');

  c = console.log;

  fs = require('fs');

  f = '/srv/mage2/esf_refine_tree.txt';

  fs.readFile(f, 'utf8', function(err, data) {
    if (err) {
      c(err);
    }
    return c(data);
  });

}).call(this);
