// Generated by CoffeeScript 1.10.0
(function() {
  var c, f, fs, parse, tabdown;

  tabdown = require('tabdown');

  c = console.log;

  fs = require('fs');

  f = '/srv/mage2/esf_refine_tree.txt';

  parse = function(tree) {
    var d, i, j, k, l, len, len1, name;
    for (name = i = 0, len = tree.length; i < len; name = ++i) {
      d = tree[name];
      for (k = l = 0, len1 = d.length; l < len1; k = ++l) {
        j = d[k];
        c(j);
      }
    }
  };

  fs.readFile(f, 'utf8', function(err, data) {
    var s, tree;
    if (err) {
      c(err);
    }
    data = data.split("\n");
    tree = tabdown.parse(data);
    s = JSON.stringify(tree);
    return c(s);
  });

}).call(this);
