// Generated by CoffeeScript 1.10.0
(function() {
  var c, convertToMagentoTree, f, fs, indentLevel, parseList, tabdown;

  tabdown = require('tabdown');

  c = console.log;

  fs = require('fs');

  f = '/srv/mage2/esf_refine_tree.txt';

  indentLevel = function(level) {
    var i, s, tab;
    s = '';
    tab = '  ';
    i = 0;
    while (i < level) {
      s += tab;
      i++;
    }
    return s;
  };

  parseList = function(data, level) {
    var i, id, j, jd, k, l, len, len1, ref, t;
    t = '';
    for (i = k = 0, len = data.length; k < len; i = ++k) {
      id = data[i];
      ref = data[i];
      for (j = l = 0, len1 = ref.length; l < len1; j = ++l) {
        jd = ref[j];
        if (j === 'toString') {
          continue;
        }
        t = indentLevel(level);
        c(t + j);
        parseList(data[i][j], level + 1);
      }
    }
  };

  convertToMagentoTree = function(data) {
    parseList(data, 0);
  };

  c('start:');

  c('');

  fs.readFile(f, 'utf8', function(err, data) {
    var tree;
    if (err) {
      c(err);
    }
    data = data.split('\n');
    tree = tabdown.parse(data);
    data = tree.root;
    convertToMagentoTree(data);
  });

}).call(this);
