// Generated by CoffeeScript 1.9.3
(function() {
  var exec, fs, implode, mgvg;

  exec = require('process-promises').exec;

  fs = require('fs');

  implode = function(sep, a) {
    return Array.prototype.join.call(a, sep);
  };

  mgvg = function(keys) {
    var cmd, i, len, r, s;
    if (keys == null) {
      keys = false;
    }
    r = implode('  | xargs -d "\\n" ag -l ', keys);
    cmd = 'ag -l ' + r;
    for (i = 0, len = keys.length; i < len; i++) {
      s = keys[i];
      cmd += ' | ag ' + s;
    }
    cmd += ' | xargs -d "\\n" grep ^ | ';
    cmd += 'ag ';
    r = implode('|', keys);
    cmd += r;
    return fs.writeFile('/tmp/testexec', cmd, function() {
      return exec('/tmp/testexec').then(function(result) {
        r = result.stdout;
        console.log(r);
      });
    });
  };

  console.log('works');

}).call(this);
